### ISSUE TITLE
Declare compatibility with Dart 2 stable

### ISSUE THREAD

**Issue by mit-mit** [google/platform.dart#17]
The Dart SDK constraint needs to be updated to [declare compatibility with Dart 2 stable](https://www.dartlang.org/dart-2#upper-constraints-on-the-sdk-version):

https://github.com/google/platform.dart/blob/master/pubspec.yaml#L12

**Comment by mit-mit** [comment]
cc @tvolkert

**Comment by mkustermann** [comment]
The next flutter/engine -> flutter/flutter roll will receive a new 2.1.0-dev Dart SDK, which requires us to upgrade all 3rd party packages. Most of them have already newer versions published which are compatible with Dart 2, but package:platform is missing.

@tvolkert @goderbauer Would you mind publishing a new version with a sdk constraint including 2.1.0? (This is blocking flutter/flutter#20427)

**Comment by tvolkert** [comment]
Fixed with #18
