### ISSUE TITLE
usages examples?

### ISSUE THREAD

**Issue by nerder** [google/platform.dart#21]
As in title i think it will be useful to provide an example of the usage.

**Comment by isorensen** [comment]
+1 ... couldn't make it work. Please add an example.

**Comment by isorensen** [comment]
I actually wrote a [Stackoverflow question](https://stackoverflow.com/questions/63329904/how-to-mock-platform-on-flutter-unit-tests) seeking some help. It's quite strange to have a google team package with zero documentation or usage examples.

**Comment by dipendra-sharma** [comment]
> I actually wrote a [Stackoverflow question](https://stackoverflow.com/questions/63329904/how-to-mock-platform-on-flutter-unit-tests) seeking some help. It's quite strange to have a google team package with zero documentation or usage examples.

Please check https://stackoverflow.com/questions/59592097/how-to-mock-a-static-getters-return-value-in-dart-or-flutter

**Comment by robert-j-webb** [comment]
Would the developers of this package be interested in a PR with a sample usage case?

**Comment by stuartmorgan** [comment]
Closing, as this package now lives in flutter/packages.

I filed https://github.com/flutter/flutter/issues/133471 to track this there.
