### ISSUE TITLE
missing IpadOS platform

### ISSUE THREAD

**Issue by lcsvcn** [google/platform.dart#22]
I found out that none of the platform libs have support for **IpadOS**.

I am currently using `
import 'dart:io' show Platform; `
and tried out this lib.

Is there any prevision to add this? I could not find the dart:io Github, so I am opening an issue here, since it is plataform related.

**Comment by dipendra-sharma** [comment]
> I found out that none of the platform libs have support for **IpadOS**.
> 
> I am currently using `import 'dart:io' show Platform;`
> and tried out this lib.
> 
> Is there any prevision to add this? I could not find the dart:io Github, so I am opening an issue here, since it is plataform related.

I think there is no 'IpadOS' platform exist. It is `ios` for Apple's iPhone or iPad.
