### ISSUE TITLE
Error: Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by BerlinLion** [google/platform.dart#32]
A lot of packages depend on this "platform" package. But this package causes error since the new version. This issue is already solved by the "universal platform" package. Isn't it possible to replace this package with that package or at least solve this error issue, which shows up now in almost every package, that I'm using for web

**Comment by mast3rmindx** [comment]
Also facing this issue very annoying..

**Comment by stuartmorgan** [comment]
Closing, as this package now lives in flutter/packages.

If this is still a problem, please [file a new issue in flutter/flutter](https://github.com/flutter/flutter/issues) (filing in all the details requested in the template there).
